/**
 * Design owner: Document 15 Phase 11 Task 11.1 (Scale Content Fixture) /
 * Task 11.5 (Synthetic Full-Content Stress Fixture) — "all 7 product
 * families, 4-5 station archetypes, dual-use examples, mastery/quality
 * metadata" at Task 11.5's ~100-product stress scale. Every ID/value is
 * generated by a loop from `manifest.ts`'s counts — no hand-authored
 * per-product content, since the point is proving the catalog/recipe-
 * graph architecture handles volume, not authoring real products.
 */
import {
  type ComponentDefinition,
  type ProductDefinition,
  type RecipeDefinition,
  type ResourceDefinition,
} from "../../domain/crafting/index.ts";
import { SCALE_PLACEHOLDER_ASSET_ID } from "./assets.ts";
import {
  componentIdForIndex,
  pad,
  productIdForIndex,
  recipeIdForIndex,
  resourceIdForIndex,
  SCALE_COMPONENT_COUNT,
  SCALE_PRODUCTS_PER_FAMILY,
  SCALE_PRODUCT_COUNT,
  SCALE_PRODUCT_FAMILIES,
  SCALE_RESOURCE_COUNT,
  SCALE_STATION_ARCHETYPES,
} from "./manifest.ts";
import { ItemId } from "../../core/ids/index.ts";

const CRAFT_DURATION_MS = 5_000;
const OUTPUT_QUANTITY = 2;
const BASE_TRANSACTION_VALUE = 10;

export const SCALE_RESOURCES: readonly ResourceDefinition[] = Array.from(
  { length: SCALE_RESOURCE_COUNT },
  (_, i): ResourceDefinition => {
    const n = i + 1;
    return {
      resourceId: resourceIdForIndex(n),
      displayName: `Scale Fixture Resource ${pad(n)}`,
      visualAssetId: SCALE_PLACEHOLDER_ASSET_ID,
      itemId: ItemId.from(`scale-resource-${pad(n)}-item`),
    };
  },
);

export const SCALE_COMPONENTS: readonly ComponentDefinition[] = Array.from(
  { length: SCALE_COMPONENT_COUNT },
  (_, i): ComponentDefinition => {
    const n = i + 1;
    return {
      componentId: componentIdForIndex(n),
      displayName: `Scale Fixture Component ${pad(n)}`,
      visualAssetId: SCALE_PLACEHOLDER_ASSET_ID,
      itemId: ItemId.from(`scale-component-${pad(n)}-item`),
    };
  },
);

/** Every recipe rank cycles 1-3; every station archetype gets a fair share of products (Task 11.1: "several Recipe Ranks"). */
function stationForProductIndex(index0: number) {
  return SCALE_STATION_ARCHETYPES[index0 % SCALE_STATION_ARCHETYPES.length]!;
}

export const SCALE_PRODUCTS: readonly ProductDefinition[] =
  SCALE_PRODUCT_FAMILIES.flatMap((family, familyIndex) =>
    Array.from(
      { length: SCALE_PRODUCTS_PER_FAMILY },
      (_, offset): ProductDefinition => {
        const index0 = familyIndex * SCALE_PRODUCTS_PER_FAMILY + offset;
        const n = index0 + 1;
        const recipeRank = (index0 % 3) + 1;
        const qualityEligible = index0 % 2 === 0;
        // Dual-use/refined-chain examples (Task 11.1): every 10th product
        // (from the 11th on) is crafted from an earlier product, exercising
        // `craftedInput` cross-references the Vertical Slice never uses.
        const craftedInput =
          n > 10 && n % 10 === 0 ? productIdForIndex(n - 10) : undefined;
        // Dual-use gear (Field Gear / Capture & Discovery Gear crossover,
        // Document 04's own "dual-use" example) — every 5th Field Gear or
        // Capture-and-Discovery product declares `playerUse`.
        const playerUse =
          (family === "FIELD_GEAR" ||
            family === "CAPTURE_AND_DISCOVERY_GEAR") &&
          offset % 5 === 0
            ? "scale-fixture-expedition-preparation"
            : undefined;
        return {
          productId: productIdForIndex(n),
          displayName: `Scale Fixture Product ${pad(n, 3)} (${family})`,
          family,
          recipeRank,
          stationType: stationForProductIndex(index0),
          routineInputs: [
            resourceIdForIndex((index0 % SCALE_RESOURCE_COUNT) + 1),
          ],
          // `Math.floor(index0 / 3)` deliberately breaks any shared factor
          // with `index0 % 3` (the recipe-rank cycle) — indexing by
          // `index0` directly left 2 of the 6 components mathematically
          // unreachable by any rank>=2 recipe (an orphan-material bug
          // Task 11.2's own registry validation caught against this exact
          // fixture during development).
          specialInputs:
            recipeRank >= 2
              ? [
                  componentIdForIndex(
                    (Math.floor(index0 / 3) % SCALE_COMPONENT_COUNT) + 1,
                  ),
                ]
              : [],
          ...(craftedInput ? { craftedInput } : {}),
          craftDuration: CRAFT_DURATION_MS,
          outputQuantity: OUTPUT_QUANTITY,
          baseTransactionValue: BASE_TRANSACTION_VALUE + recipeRank * 5,
          displayCategory: family.toLowerCase().replaceAll("_", "-"),
          demandTags: ["scale-fixture"],
          ...(playerUse ? { playerUse } : {}),
          masteryProfile: "scale-fixture-no-mastery-tuning",
          qualityEligible,
          unlockRequirements: [],
          catchmonHooks: [],
          visualAssetId: SCALE_PLACEHOLDER_ASSET_ID,
        };
      },
    ),
  );

export const SCALE_RECIPES: readonly RecipeDefinition[] = SCALE_PRODUCTS.map(
  (product, index0): RecipeDefinition => {
    const n = index0 + 1;
    return {
      recipeId: recipeIdForIndex(n),
      displayName: `Craft ${product.displayName}`,
      outputProductId: product.productId,
      stationType: product.stationType,
      recipeRank: product.recipeRank,
      routineInputs: product.routineInputs.map((resourceId) => ({
        resourceId,
        quantity: 1,
      })),
      specialInputs: product.specialInputs.map((componentId) => ({
        componentId,
        quantity: 1,
      })),
      ...(product.craftedInput ? { craftedInput: product.craftedInput } : {}),
      craftDuration: product.craftDuration,
      unlockRequirements: [],
    };
  },
);

if (SCALE_PRODUCTS.length !== SCALE_PRODUCT_COUNT) {
  throw new Error(
    `scale-fixture crafting.ts generated ${String(SCALE_PRODUCTS.length)} products, expected ${String(SCALE_PRODUCT_COUNT)} — generator/manifest drifted apart.`,
  );
}
