/**
 * Design owner: Document 15 Phase 11 (Scale Validation), Tasks 11.1/11.5.
 *
 * The one source of scale-fixture counts and ID-naming — mirrors
 * `content/vertical-slice/verticalSliceManifest.ts`'s role as "the single
 * reserved-ID source," except every ID here is generated by a loop, not
 * hand-authored, since Phase 11's whole point is proving the architecture
 * survives content volume the Vertical Slice never exercises.
 *
 * NOT canonical production content (CLAUDE.md Phase 11 instruction: "Do
 * NOT turn synthetic content into canonical production content"). Every
 * display name below says "Scale Fixture" so nothing here could be
 * mistaken for real game content in a screenshot or save file. The only
 * non-synthetic facts reused are the 17 canonical `ElementId`s (Document
 * 09/CLAUDE.md §9 locked identity) and the fixed `ProductFamily`/
 * `StationArchetype`/`CatchmonDomain`/`Rarity`/`CustomerLayer`/
 * `ExpeditionIntent` unions, which are architecture, not content.
 */
import { ELEMENT_IDS, type ElementId } from "../../domain/world/index.ts";
import { type ProductFamily } from "../../domain/crafting/index.ts";
import { type StationArchetype } from "../../domain/crafting/index.ts";
import { type Rarity } from "../../domain/catchmons/index.ts";
import {
  CapabilityId,
  CatchmonLineId,
  CatchmonSpeciesId,
  ComponentId,
  CustomerArchetypeId,
  DisplaySlotId,
  InfrastructureId,
  OrderId,
  ProductId,
  RecipeId,
  RegionId,
  ResourceId,
  RouteId,
  StationId,
  UnlockRuleId,
} from "../../core/ids/index.ts";

/** One region per canonical element (17) — the exact scale target the task specifies. */
export const SCALE_REGION_COUNT = ELEMENT_IDS.length;
export const SCALE_ROUTES_PER_REGION = 2;

/** ~100 products/recipes (Document 15 Task 11.5's stress target), split evenly across all 7 fixed product families. */
export const SCALE_PRODUCT_FAMILIES: readonly ProductFamily[] = [
  "PROVISIONS",
  "CARE_AND_COMFORT",
  "WEARABLES",
  "FIELD_GEAR",
  "CAPTURE_AND_DISCOVERY_GEAR",
  "ELEMENTAL_CRAFT",
  "HABITAT_AND_ENRICHMENT",
];
export const SCALE_PRODUCTS_PER_FAMILY = 14;
export const SCALE_PRODUCT_COUNT =
  SCALE_PRODUCT_FAMILIES.length * SCALE_PRODUCTS_PER_FAMILY;
export const SCALE_RESOURCE_COUNT = 6;
export const SCALE_COMPONENT_COUNT = 6;

/** All 5 fixed station archetypes, 2 station instances each — "multiple stations" beyond the slice's 2. */
export const SCALE_STATION_ARCHETYPES: readonly StationArchetype[] = [
  "PROVISION_STATION",
  "CARE_ATELIER",
  "FIELDWORKS_BENCH",
  "RESONANCE_LAB",
  "HABITAT_WORKSHOP",
];
export const SCALE_STATIONS_PER_ARCHETYPE = 2;
export const SCALE_STATION_COUNT =
  SCALE_STATION_ARCHETYPES.length * SCALE_STATIONS_PER_ARCHETYPE;

export const SCALE_DISPLAY_SLOT_COUNT = 6;

/** Mixed 1/2/3-stage evolution lines summing to exactly 104 species (Document 15 Task 11.5). */
export const SCALE_SINGLE_STAGE_LINE_COUNT = 30;
export const SCALE_TWO_STAGE_LINE_COUNT = 25;
export const SCALE_THREE_STAGE_LINE_COUNT = 8;
export const SCALE_LINE_COUNT =
  SCALE_SINGLE_STAGE_LINE_COUNT +
  SCALE_TWO_STAGE_LINE_COUNT +
  SCALE_THREE_STAGE_LINE_COUNT;
export const SCALE_SPECIES_COUNT =
  SCALE_SINGLE_STAGE_LINE_COUNT * 1 +
  SCALE_TWO_STAGE_LINE_COUNT * 2 +
  SCALE_THREE_STAGE_LINE_COUNT * 3;
export const SCALE_STARTER_SPECIES_COUNT = 6;

export const SCALE_RARITIES: readonly Rarity[] = [
  "COMMON",
  "RARE",
  "LEGENDARY",
  "MYTHIC",
  "GOD",
];

export const SCALE_CUSTOMER_ARCHETYPE_COUNT = 8;
export const SCALE_INFRASTRUCTURE_COUNT = 10;
export const SCALE_PROGRESSION_UNLOCK_COUNT = 10;
export const SCALE_ORDER_COUNT = 10;

/** Zero-padded index, e.g. `pad(3, 2) === "03"` — stable, sortable synthetic IDs. */
export function pad(index: number, width = 2): string {
  return String(index).padStart(width, "0");
}

/** Canonical element for region/species index `i` (wraps if the caller asks for more than 17). */
export function elementForIndex(i: number): ElementId {
  return ELEMENT_IDS[i % ELEMENT_IDS.length]!;
}

// ---- Centralized ID generators (one place, so no two content files can
// accidentally diverge on how a given index is named) ----

export const regionIdForIndex = (i: number): RegionId =>
  RegionId.from(`scale-region-${pad(i)}`);
export const routeIdForIndex = (
  regionIndex: number,
  routeIndex: number,
): RouteId =>
  RouteId.from(`scale-route-${pad(regionIndex)}-${pad(routeIndex)}`);
export const resourceIdForIndex = (i: number): ResourceId =>
  ResourceId.from(`scale-resource-${pad(i)}`);
export const componentIdForIndex = (i: number): ComponentId =>
  ComponentId.from(`scale-component-${pad(i)}`);
export const productIdForIndex = (i: number): ProductId =>
  ProductId.from(`scale-product-${pad(i, 3)}`);
export const recipeIdForIndex = (i: number): RecipeId =>
  RecipeId.from(`scale-recipe-${pad(i, 3)}`);
export const stationIdForIndex = (i: number): StationId =>
  StationId.from(`scale-station-${pad(i)}`);
export const displaySlotIdForIndex = (i: number): DisplaySlotId =>
  DisplaySlotId.from(`scale-display-${pad(i)}`);
export const lineIdForIndex = (i: number): CatchmonLineId =>
  CatchmonLineId.from(`scale-line-${pad(i, 3)}`);
export const speciesIdForIndex = (i: number): CatchmonSpeciesId =>
  CatchmonSpeciesId.from(`scale-species-${pad(i, 3)}`);
export const capabilityIdForIndex = (i: number): CapabilityId =>
  CapabilityId.from(`scale-capability-${pad(i, 3)}`);
export const customerArchetypeIdForIndex = (i: number): CustomerArchetypeId =>
  CustomerArchetypeId.from(`scale-customer-archetype-${pad(i)}`);
export const infrastructureIdForIndex = (i: number): InfrastructureId =>
  InfrastructureId.from(`scale-infrastructure-${pad(i)}`);
export const orderIdForIndex = (i: number): OrderId =>
  OrderId.from(`scale-order-${pad(i)}`);
export const unlockRuleIdForIndex = (i: number): UnlockRuleId =>
  UnlockRuleId.from(`scale-unlock-rule-${pad(i)}`);
export const progressionUnlockRuleIdForIndex = (i: number): UnlockRuleId =>
  UnlockRuleId.from(`scale-progression-unlock-${pad(i)}`);
