/**
 * Design owner: Document 15 Task 08.1 (Application Providers / Stores);
 * CLAUDE.md §13 Balance Rule.
 *
 * The one place every command/reconciliation-pass factory's PROVISIONAL
 * config object is assembled from `content/vertical-slice`'s centralized
 * balance constants — so `register-commands.ts`/`reconciliation-passes.ts`
 * read one typed config object each, rather than importing two dozen
 * balance constants directly. No new values are invented here; every
 * number below already exists in `content/vertical-slice/balance.ts`.
 */
import { type GameCatalog } from "../domain/catalog/index.ts";
import {
  PLAYABLE_DISPLAY_SLOT_IDS,
  PROVISIONAL_BASE_CAPTURE_CHANCE,
  PROVISIONAL_CAPABILITY_MAGNITUDES,
  PROVISIONAL_CAPTURE_AID_BONUS,
  PROVISIONAL_CAPTURE_CHANCE_CEILING,
  PROVISIONAL_CAPTURE_CHANCE_FLOOR,
  PROVISIONAL_CAPTURE_PROTECTION_BONUS_PER_FAILURE,
  PROVISIONAL_CATCHMON_LEVEL_CAP,
  PROVISIONAL_COMPONENT_HUNT_BONUS_CHANCE,
  PROVISIONAL_COMPONENT_HUNT_PROTECTION_THRESHOLD,
  PROVISIONAL_COMPONENT_HUNT_ROUTINE_REWARD_QUANTITY,
  PROVISIONAL_DISCOVERY_SURVEY_ROUTINE_REWARD_QUANTITY,
  PROVISIONAL_EVOLUTION_LEVEL_REQUIREMENT,
  PROVISIONAL_MAX_ACTIVE_CUSTOMERS,
  PROVISIONAL_MAX_CONCURRENT_EXPEDITIONS,
  PROVISIONAL_MAX_QUEUE_SIZE,
  PROVISIONAL_MAX_SHOP_FLOOR_SUPPORT_SLOTS,
  PROVISIONAL_MAX_WORKSHOP_SUPPORT_PER_STATION,
  PROVISIONAL_MIN_ARRIVAL_INTERVAL_MS,
  PROVISIONAL_OBSERVE_ENCOUNTER_REWARD_QUANTITY,
  PROVISIONAL_RANK_PROGRESS_PER_CAPTURE,
  PROVISIONAL_RANK_PROGRESS_PER_CRAFT_COMPLETION,
  PROVISIONAL_RANK_PROGRESS_PER_EXPEDITION_COMPLETION,
  PROVISIONAL_RANK_PROGRESS_PER_RANK,
  PROVISIONAL_SHOP_RANK_CAP,
  PROVISIONAL_SUPPLY_RUN_ROUTINE_REWARD_QUANTITY,
  PROVISIONAL_XP_PER_CRAFT_COMPLETION,
  PROVISIONAL_XP_PER_EXPEDITION_COMPLETION,
  PROVISIONAL_XP_PER_LEVEL,
  PROVISIONAL_XP_PER_SALE_RESOLUTION,
  SLICE_CUSTOMER_ARCHETYPES,
  SLICE_DISPLAY_SLOT_UNLOCK_REQUIREMENTS,
  SLICE_PRODUCT_04_ID,
  SLICE_RESOURCE_A_ID,
  SLICE_ROUTE_DURATION_MS,
  SLICE_SHOP_FLOOR_SUPPORT_SLOT_ID,
  COMPONENT_HUNT_ROUTE_ID,
  DISCOVERY_SURVEY_ROUTE_ID,
  SUPPLY_RUN_ROUTE_ID,
  OZEAN_TIDAL_SHALLOWS_ROUTE_ID,
  OZEAN_REEF_SURVEY_ROUTE_ID,
  OZEAN_TIDEPOOL_HUNT_ROUTE_ID,
  OZEAN_RESOURCE_REEF_KELP_ID,
  OZEAN_RESOURCE_CLEANSING_BRINE_ID,
  EXPEDITION_HUB_INFRASTRUCTURE_ID,
  VERTICAL_SLICE_STATION_ARCHETYPES,
} from "../content/vertical-slice/index.ts";
import {
  PROVISIONAL_BASE_STATS_CONFIG,
  PROVISIONAL_BATTLE_PATH_BONUSES,
  PROVISIONAL_BOND_LEVEL_CAP,
  PROVISIONAL_BOND_PROGRESS_PER_BATTLE,
  PROVISIONAL_BOND_PROGRESS_PER_BOND_LEVEL,
  PROVISIONAL_BOND_SUPPORT_BONUS_PER_LEVEL,
  PROVISIONAL_EVOLUTION_STAGE_ATTACK_BONUS,
  PROVISIONAL_EVOLUTION_STAGE_DEFENSE_BONUS,
  PROVISIONAL_EVOLUTION_STAGE_HP_BONUS,
  PROVISIONAL_FORGES_PER_FORGE_LEVEL,
  PROVISIONAL_FORGE_LEVEL_CAP,
  PROVISIONAL_FORGE_RELIC_ECHO_CHARGE_COST,
  PROVISIONAL_INSIGHT_GAIN_PER_RECYCLE,
  PROVISIONAL_INSIGHT_GUARANTEED_MINIMUM_RARITY,
  PROVISIONAL_INSIGHT_GUARANTEE_THRESHOLD,
  PROVISIONAL_MAX_ROUNDS,
  PROVISIONAL_POWER_WEIGHTS,
  PROVISIONAL_RECYCLE_COINS_BY_RARITY,
  PROVISIONAL_RELIC_GENERATION_CONFIG,
  COMBAT_SLICE_BOND_SUPPORT_BEHAVIORS,
  PROVISIONAL_JOURNEY_RANK_PROGRESS_PER_NORMAL_WIN,
  PROVISIONAL_JOURNEY_RANK_PROGRESS_PER_BOSS_WIN,
  PROVISIONAL_JOURNEY_RANK_PROGRESS_PER_RANK,
  PROVISIONAL_JOURNEY_RANK_CAP,
  PROVISIONAL_EXPEDITION_ECHO_CHARGE_REWARD,
  PROVISIONAL_OFFLINE_CLEARS_PER_HOUR,
  PROVISIONAL_OFFLINE_EFFICIENCY_BPS,
  PROVISIONAL_OFFLINE_MAX_HOURS,
} from "../content/combat-slice/index.ts";

export function buildGameConfig(catalog: GameCatalog) {
  const observeRewardItemId =
    catalog.resources.get(SLICE_RESOURCE_A_ID)!.itemId;

  const saleXpConfig = {
    xpPerSaleResolution: PROVISIONAL_XP_PER_SALE_RESOLUTION,
    xpPerLevel: PROVISIONAL_XP_PER_LEVEL,
    levelCap: PROVISIONAL_CATCHMON_LEVEL_CAP,
  };

  return {
    stationArchetypes: VERTICAL_SLICE_STATION_ARCHETYPES,
    displaySlotIds: PLAYABLE_DISPLAY_SLOT_IDS,
    maxQueueSize: PROVISIONAL_MAX_QUEUE_SIZE,
    catchmonCapabilityMagnitudes: PROVISIONAL_CAPABILITY_MAGNITUDES,
    maxWorkshopSupportPerStation: PROVISIONAL_MAX_WORKSHOP_SUPPORT_PER_STATION,
    shopFloorSupportSlotId: SLICE_SHOP_FLOOR_SUPPORT_SLOT_ID,
    maxShopFloorSupportSlots: PROVISIONAL_MAX_SHOP_FLOOR_SUPPORT_SLOTS,
    evolutionLevelRequirement: PROVISIONAL_EVOLUTION_LEVEL_REQUIREMENT,
    displaySlotUnlockRequirements: SLICE_DISPLAY_SLOT_UNLOCK_REQUIREMENTS,
    customerArchetypes: SLICE_CUSTOMER_ARCHETYPES,
    maxActiveCustomers: PROVISIONAL_MAX_ACTIVE_CUSTOMERS,
    minArrivalIntervalMs: PROVISIONAL_MIN_ARRIVAL_INTERVAL_MS,
    saleXpConfig,
    expeditionHubInfrastructureId: EXPEDITION_HUB_INFRASTRUCTURE_ID,
    captureAidProductId: SLICE_PRODUCT_04_ID,
    routeDurationMsByRouteId: SLICE_ROUTE_DURATION_MS,
    maxConcurrentExpeditions: PROVISIONAL_MAX_CONCURRENT_EXPEDITIONS,
    captureChanceConfig: {
      base: PROVISIONAL_BASE_CAPTURE_CHANCE,
      aidBonus: PROVISIONAL_CAPTURE_AID_BONUS,
      protectionBonusPerFailure:
        PROVISIONAL_CAPTURE_PROTECTION_BONUS_PER_FAILURE,
      floor: PROVISIONAL_CAPTURE_CHANCE_FLOOR,
      ceiling: PROVISIONAL_CAPTURE_CHANCE_CEILING,
    },
    captureRankProgressConfig: {
      progressPerCapture: PROVISIONAL_RANK_PROGRESS_PER_CAPTURE,
      progressPerRank: PROVISIONAL_RANK_PROGRESS_PER_RANK,
      rankCap: PROVISIONAL_SHOP_RANK_CAP,
    },
    observeRewardItemId,
    observeRewardQuantity: PROVISIONAL_OBSERVE_ENCOUNTER_REWARD_QUANTITY,
    craftXpConfig: {
      xpPerCraftCompletion: PROVISIONAL_XP_PER_CRAFT_COMPLETION,
      xpPerLevel: PROVISIONAL_XP_PER_LEVEL,
      levelCap: PROVISIONAL_CATCHMON_LEVEL_CAP,
    },
    craftRankProgressConfig: {
      progressPerCraftCompletion:
        PROVISIONAL_RANK_PROGRESS_PER_CRAFT_COMPLETION,
      progressPerRank: PROVISIONAL_RANK_PROGRESS_PER_RANK,
      rankCap: PROVISIONAL_SHOP_RANK_CAP,
    },
    expeditionRewardConfig: {
      // Ozean Batch A closure: each route now grants its own real routine
      // resource (Vulkankrater's 3 routes unchanged, still
      // SLICE_RESOURCE_A_ID). Tidal Shallows -> Reef Kelp (the explicit
      // "must actually grant its intended routine Water resource"); Reef
      // Survey also grants Reef Kelp (matching Vulkankrater's own pattern
      // of Discovery Survey granting the region's primary routine
      // resource, Document 07 §47); Tidepool Hunt grants Cleansing Brine
      // as its routine reward (its special-component opportunity, Luminous
      // Pearl, is separate and already flows through `specialComponentPool`
      // below, untouched by this change).
      routineRewardResourceIdByRouteId: {
        [SUPPLY_RUN_ROUTE_ID]: SLICE_RESOURCE_A_ID,
        [DISCOVERY_SURVEY_ROUTE_ID]: SLICE_RESOURCE_A_ID,
        [COMPONENT_HUNT_ROUTE_ID]: SLICE_RESOURCE_A_ID,
        [OZEAN_TIDAL_SHALLOWS_ROUTE_ID]: OZEAN_RESOURCE_REEF_KELP_ID,
        [OZEAN_REEF_SURVEY_ROUTE_ID]: OZEAN_RESOURCE_REEF_KELP_ID,
        [OZEAN_TIDEPOOL_HUNT_ROUTE_ID]: OZEAN_RESOURCE_CLEANSING_BRINE_ID,
      },
      routineRewardQuantityByRouteId: {
        [SUPPLY_RUN_ROUTE_ID]: PROVISIONAL_SUPPLY_RUN_ROUTINE_REWARD_QUANTITY,
        [DISCOVERY_SURVEY_ROUTE_ID]:
          PROVISIONAL_DISCOVERY_SURVEY_ROUTINE_REWARD_QUANTITY,
        [COMPONENT_HUNT_ROUTE_ID]:
          PROVISIONAL_COMPONENT_HUNT_ROUTINE_REWARD_QUANTITY,
        [OZEAN_TIDAL_SHALLOWS_ROUTE_ID]:
          PROVISIONAL_SUPPLY_RUN_ROUTINE_REWARD_QUANTITY,
        [OZEAN_REEF_SURVEY_ROUTE_ID]:
          PROVISIONAL_DISCOVERY_SURVEY_ROUTINE_REWARD_QUANTITY,
        [OZEAN_TIDEPOOL_HUNT_ROUTE_ID]:
          PROVISIONAL_COMPONENT_HUNT_ROUTINE_REWARD_QUANTITY,
      },
      componentHuntBonusChance: PROVISIONAL_COMPONENT_HUNT_BONUS_CHANCE,
      componentHuntProtectionThreshold:
        PROVISIONAL_COMPONENT_HUNT_PROTECTION_THRESHOLD,
      echoChargeRewardPerCompletion: PROVISIONAL_EXPEDITION_ECHO_CHARGE_REWARD,
    },
    expeditionXpConfig: {
      xpPerExpeditionCompletion: PROVISIONAL_XP_PER_EXPEDITION_COMPLETION,
      xpPerLevel: PROVISIONAL_XP_PER_LEVEL,
      levelCap: PROVISIONAL_CATCHMON_LEVEL_CAP,
    },
    expeditionRankProgressConfig: {
      progressPerExpeditionCompletion:
        PROVISIONAL_RANK_PROGRESS_PER_EXPEDITION_COMPLETION,
      progressPerRank: PROVISIONAL_RANK_PROGRESS_PER_RANK,
      rankCap: PROVISIONAL_SHOP_RANK_CAP,
    },

    // ---- docs/rebuild/15 Phases R2-R5 ----
    leadStatsConfig: {
      baseStatsConfig: PROVISIONAL_BASE_STATS_CONFIG,
      battlePathBonuses: PROVISIONAL_BATTLE_PATH_BONUSES,
      bondSupportBehaviors: COMBAT_SLICE_BOND_SUPPORT_BEHAVIORS,
      bondSupportBonusPerLevel: PROVISIONAL_BOND_SUPPORT_BONUS_PER_LEVEL,
      evolutionStageAttackBonus: PROVISIONAL_EVOLUTION_STAGE_ATTACK_BONUS,
      evolutionStageHpBonus: PROVISIONAL_EVOLUTION_STAGE_HP_BONUS,
      evolutionStageDefenseBonus: PROVISIONAL_EVOLUTION_STAGE_DEFENSE_BONUS,
    },
    powerWeights: PROVISIONAL_POWER_WEIGHTS,
    attemptStageConfig: {
      maxRounds: PROVISIONAL_MAX_ROUNDS,
      bondProgressPerBattle: PROVISIONAL_BOND_PROGRESS_PER_BATTLE,
      bondProgressPerBondLevel: PROVISIONAL_BOND_PROGRESS_PER_BOND_LEVEL,
      bondLevelCap: PROVISIONAL_BOND_LEVEL_CAP,
      journeyRankProgressPerNormalWin:
        PROVISIONAL_JOURNEY_RANK_PROGRESS_PER_NORMAL_WIN,
      journeyRankProgressPerBossWin:
        PROVISIONAL_JOURNEY_RANK_PROGRESS_PER_BOSS_WIN,
      journeyRankProgressPerRank: PROVISIONAL_JOURNEY_RANK_PROGRESS_PER_RANK,
      journeyRankCap: PROVISIONAL_JOURNEY_RANK_CAP,
    },
    journeyOfflineConfig: {
      clearsPerHour: PROVISIONAL_OFFLINE_CLEARS_PER_HOUR,
      efficiencyBps: PROVISIONAL_OFFLINE_EFFICIENCY_BPS,
      maxHours: PROVISIONAL_OFFLINE_MAX_HOURS,
    },
    forgeRelicConfig: {
      echoChargeCost: PROVISIONAL_FORGE_RELIC_ECHO_CHARGE_COST,
      forgesPerLevel: PROVISIONAL_FORGES_PER_FORGE_LEVEL,
      forgeLevelCap: PROVISIONAL_FORGE_LEVEL_CAP,
      insightGuaranteeThreshold: PROVISIONAL_INSIGHT_GUARANTEE_THRESHOLD,
      insightGuaranteedMinimumRarity:
        PROVISIONAL_INSIGHT_GUARANTEED_MINIMUM_RARITY,
      relicGenerationConfig: PROVISIONAL_RELIC_GENERATION_CONFIG,
    },
    recycleRelicConfig: {
      coinsByRarity: PROVISIONAL_RECYCLE_COINS_BY_RARITY,
      insightGainPerRecycle: PROVISIONAL_INSIGHT_GAIN_PER_RECYCLE,
    },
    maxEquippedSkills: 3,
  };
}

export type GameConfig = ReturnType<typeof buildGameConfig>;
